feat: добавить itemRequest, тесты
Kadyke/java-shareit pull request #3
Opened 2023-06-28 12:31 UTC by Kadyke

2023-06-29 15:30 UTC, db-exp requested changes

2023-06-29 15:30 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        State state;
дублирует код выше - может вынесем?

2023-06-29 15:30 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (from == null || size == null) {
тоже проверки дублируются - давай сделаем валидатор, а для status можно сделать аннотацию валидации свою

2023-06-29 15:30 UTC, db-exp commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTest.java
> +    @Transactional
а зачем на тестах Transactional?

2023-06-29 15:30 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        switch (state) {
хорошая практика - всегда делать default

2023-06-29 15:30 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        if (from == null || size == null) {
тут и ниже стоит вынести проверки в одно место и переиспользовать

2023-06-29 17:05 UTC, Kadyke commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTest.java
> +    @Transactional
Иначе они сыпятся в гите, локально все проходит

2023-06-30 06:33 UTC, Kadyke commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        State state;
+

2023-06-30 06:33 UTC, Kadyke commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (from == null || size == null) {
+

2023-06-30 06:33 UTC, Kadyke commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        if (from == null || size == null) {
+

2023-06-30 07:38 UTC, db-exp approved these changes

2023-06-30 08:15 UTC, merged