Add docker
Kadyke/java-shareit pull request #4
Opened 2023-07-02 18:48 UTC by Kadyke

2023-07-03 16:31 UTC, db-exp requested changes

2023-07-03 16:31 UTC, db-exp commented on pom.xml
можно удалить dependencies из этого pom'а

2023-07-03 19:40 UTC, db-exp approved these changes

2023-07-13 04:02 UTC, Kadyke commented
dfsdf

2023-07-13 04:02 UTC, merged